/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ubudu.serverdate.core;

public class http_get_interface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected http_get_interface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(http_get_interface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        server_date_native_WrapperJNI.delete_http_get_interface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    server_date_native_WrapperJNI.http_get_interface_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    server_date_native_WrapperJNI.http_get_interface_change_ownership(this, swigCPtr, true);
  }

  public String get(String url) {
    return server_date_native_WrapperJNI.http_get_interface_get(swigCPtr, this, url);
  }

  public http_get_interface() {
    this(server_date_native_WrapperJNI.new_http_get_interface(), true);
    server_date_native_WrapperJNI.http_get_interface_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
